(function(){'use strict';
const $=id=>document.getElementById(id), L=window.KuiperCodexLogic, DATA=window.KuiperCodeData, SOUND=window.KuiperSound;
const canvas=$('canvas'),g=canvas.getContext('2d'), TAU=Math.PI*2;
const palettes={kuiper:['#00ffff','#66ccff','#ffb000','#22ee77','#ffffff'],paper:['#ffffff','#00ffff','#ffb000','#ffffff','#66ccff'],ember:['#ffb000','#ff8d65','#ffffc0','#ffffff','#00ffff'],ocean:['#66ccff','#00ffff','#22ee77','#ffffff','#aabfff'],orchid:['#ebadff','#00ffff','#ffd0e5','#ffffff','#ffb000']};
const state={params:L.normalize({...L.defaults(),first:1,offset:0,degreesPerKey:137.5}),lever:0,shadows:false,selected:1,practice:null,free:false,nearest:null,code:false,colour:'age',palette:'kuiper',magnifier:false,playing:false,speed:2,revealed:1,wonder:false,wonderStart:0,wonderIndex:-1,morph:null,text:24,proof:null,proving:false,realEstate:false,unsafeInput:false};
let width=0,height=0,cam={cx:0,cy:0,s:1,x:0,y:0},frame=0,lastPlay=0,lastHint=0,hintTimer=0,drag=null,hit=[],sample=[],dirty=true;
const number=n=>Number.isFinite(n)?(Number.isInteger(n)?n.toLocaleString('en-GB',{maximumFractionDigits:0}):n.toLocaleString('en-GB',{maximumFractionDigits:5})):String(n);
const editNumber=n=>Number.isFinite(n)?(Number.isInteger(n)?String(n):String(Number(n.toPrecision(12)))):String(n);
const compact=n=>!Number.isFinite(n)?String(n):Math.abs(n)>=1e15?(n/1e15).toLocaleString('en-GB',{maximumFractionDigits:2})+' quadrillion':Math.abs(n)>=1e12?(n/1e12).toLocaleString('en-GB',{maximumFractionDigits:2})+' trillion':Math.abs(n)>=1e9?(n/1e9).toLocaleString('en-GB',{maximumFractionDigits:2})+' billion':Math.abs(n)>=1e6?(n/1e6).toLocaleString('en-GB',{maximumFractionDigits:2})+' million':number(n);
const numeric=s=>Number(String(s).replaceAll(',','').trim());
function unsafeIntegerText(s){const t=String(s).replaceAll(',','').trim();if(!/^[+\-]?\d+$/.test(t))return false;try{return BigInt(t)>9007199254740992n||BigInt(t)<-9007199254740992n;}catch(e){return false;}}
function params(){return state.params;}
function truePoint(){return L.place(state.selected,params());}
function currentPoint(){return state.practice||truePoint();}
function log(command,result){const rows=$('command-log').children;rows[0].textContent='> '+command;rows[1].textContent=result;}
function status(text){const full=String(text);$('status').textContent=innerWidth<700&&full.startsWith('ALL OF THIS')?'ONE NUMBER. ONE RULE. NO COORDINATES STORED.':full.length>95?full.split('. ')[0]+'.':full;$('status').title=full;}
function invalidate(){dirty=true;}
function stopWonder(){if(state.wonder){state.wonder=false;$('wonder').hidden=true;try{localStorage.setItem('kuiper-codex-wonder','seen');}catch(e){}}}
let firstGesture=true;
function gesture(e){SOUND.awaken();if(firstGesture){firstGesture=false;SOUND.tone(1,1);}$('mute').textContent=SOUND.muted?'Sound off':'Sound on';if(state.wonder&&e&&e.target.id!=='skip')stopWonder();}
document.addEventListener('pointerdown',gesture,{capture:true});document.addEventListener('keydown',e=>{if(e.isTrusted)gesture(e);},{capture:true});
function inputValue(id,value){if($(id)&&document.activeElement!==$(id))$(id).value=value;}
function sourceForKey(key){if(!DATA||!DATA.lines.length)return null;let index=1;if(state.code){const p=params(),gap=Math.floor(p.skipPerSecond*Math.min(p.restSeconds,p.capSeconds)),work=gap>0?p.workLines:1,delta=key-p.first,cycle=work+gap;index=gap>0?Math.floor(delta/cycle)*work+delta%cycle:delta;if(!Number.isSafeInteger(index)||index<0||index>=DATA.lines.length)return null;}return DATA.lines[index];}
function setParams(change,{smooth=true,quiet=false}={}){const before=params();state.params=L.normalize({...before,...change,_raw:{...before._raw,...change}});state.practice=null;state.free=false;state.nearest=null;state.realEstate=false;if(smooth&&!matchMedia('(prefers-reduced-motion: reduce)').matches)state.morph={from:before,t:performance.now()};state.revealed=Math.min(Math.max(1,state.revealed),params().count);const b=L.bounds(params());if(Number.isFinite(params().first)&&params().count===1)state.selected=params().first;else if(b.valid&&(state.selected<b.first||state.selected>b.last))state.selected=b.first;sync();invalidate();if(!quiet)status(L.describe(params()).join(' '));return state.params;}
function selectKey(key){key=numeric(key);state.selected=key;state.practice=null;state.free=false;state.nearest=null;sync();invalidate();return truePoint();}
function moveSelected(x,y){x=numeric(x);y=numeric(y);if(!Number.isFinite(x)||!Number.isFinite(y)){status('That is not a finite place. The numbers stay yours to change.');return;}state.practice={key:state.selected,x,y,r:Math.hypot(x,y),deg:((Math.atan2(y,x)*180/Math.PI)%360+360)%360,valid:true};state.practice.theta=state.practice.deg*Math.PI/180;state.free=true;try{state.nearest=L.pick(x,y,params(),{budget:512});}catch(e){state.nearest=null;}sync();invalidate();status('Your practice dot moved. The small cross marks its true place.');return state.practice;}
function movePolar(r,deg){r=numeric(r);deg=numeric(deg);if(!Number.isFinite(r)||!Number.isFinite(deg)||r<0){status('A drawable distance is finite and nonnegative. Your entry has not been clamped.');return;}const a=deg*Math.PI/180;moveSelected(r*Math.cos(a),r*Math.sin(a));}
function sync(){const p=currentPoint(),lawPoint=truePoint(),count=params().count,phone=innerWidth<700; $('count-label').textContent=compact(count)+(count===1?' particle addressed':' addressed');$('key-label').textContent=compact(state.selected);inputValue('angle',params().degreesPerKey===null?Number((360*params().turnNumber/params().wrap).toFixed(4)):editNumber(params().degreesPerKey));inputValue('lever-power',params().power);inputValue('lever-count',params()._raw.count??params().count);inputValue('lever-quiet',params().restSeconds);const source=sourceForKey(state.selected);$('source-line').textContent=source?(source.text||'[blank line, kept]'):'Public Kuiper code';$('source-caption').textContent=source?source.path+':'+source.line+' · example key':'Example address';$('source-line').title=source?.text||'';
 $('layer-label').textContent=L.isReal(params())?'THE REAL KUIPER':'YOUR SPIRAL · PRACTICE';$('header-layer').textContent=L.isReal(params())?'REAL KUIPER':'YOUR SPIRAL';$('next-lever').hidden=state.lever>=5;$('numbers').hidden=state.lever<5;$('play').hidden=state.lever<2;$('reset').hidden=state.lever<5;
 document.querySelectorAll('[data-level]').forEach(el=>el.hidden=Number(el.dataset.level)>state.lever);$('magnify').hidden=state.lever<2;
 $('formula-radius').textContent=phone?(params().power===.5?'R=√('+number(state.selected)+(params().offset===0?'':(params().offset<0?'':'+')+number(params().offset))+')='+number(lawPoint.r):'R=('+number(state.selected)+'+'+number(params().offset)+')^'+number(params().power)+'='+number(lawPoint.r)):(params().power===.5?'DISTANCE = √('+number(state.selected)+(params().offset===0?'':' + '+number(params().offset))+') = '+number(lawPoint.r):'DISTANCE = ('+number(state.selected)+' + '+number(params().offset)+') ^ '+number(params().power)+' = '+number(lawPoint.r));
 $('formula-turn').textContent=params().degreesPerKey===null?'TURN = MOD(KEY × '+params().turnNumber+' / '+params().wrap+', 1) TURNS':'TURN = KEY × '+number(params().degreesPerKey)+'°; FULL LAPS REMOVED';
 const degrees=params().degreesPerKey===null?params().turnNumber/params().wrap*360:params().degreesPerKey;const raw=state.selected*degrees;const laps=Math.floor(raw/360);const left=number(lawPoint.deg);$('sample-label').textContent=state.practice?(phone?'MOVED R=':'PRACTICE DISTANCE ')+(phone?Number(p.r.toFixed(2)):number(p.r))+' / '+(phone?Number(p.deg.toFixed(2)):number(p.deg))+'°':state.code?(phone?'REAL CODE / DEMO KEYS':'REAL SOURCE LINES. EXAMPLE ADDRESSES.'):state.lever===0?(phone?(Math.abs(raw)>Number.MAX_SAFE_INTEGER?'~':'')+number(laps)+' LAPS / '+left+'° LEFT':number(raw)+'° = '+number(laps)+' FULL LAPS + '+left+'°'):count>3000?'A fair sample. No coordinate table.':(phone?'R='+Number(p.r.toFixed(2))+' / '+Number(p.deg.toFixed(2))+'°':'DISTANCE '+number(p.r)+' / TURN '+number(p.deg)+'°');
 $('play').textContent=state.playing?'Pause':'Play';$('magnify').setAttribute('aria-pressed',String(state.magnifier));
 for(const [name] of fieldSpecs){const input=$('param-'+name);if(input&&document.activeElement!==input)input.value=params()[name]===null?'':String(params()._raw[name]??params()[name]);}
 const real=L.place(state.selected,L.defaults());const direction=directionOf(real.deg);$('real-instructions').textContent='Press / on the live site, type '+number(state.selected)+', then Enter. Ring '+number(Math.floor(real.r))+'. Look '+direction+' from the centre. Distance '+number(real.r)+'.';
 const interval=findInterval(state.selected);$('real-provenance').textContent=interval?'This historical address is issued. The code shown here is a separately labelled Kuiper source example.':'This historical address is in a quiet gap. The live site may show its marker, but there is no issued particle here.';
 $('nearest-label').textContent=state.nearest&&Number.isFinite(state.nearest.key)?'Nearest '+(state.nearest.certified?'certified':'candidate')+' key: '+number(state.nearest.key)+(state.nearest.reason?' · '+state.nearest.reason:''):state.practice?'Free placement. Select a finite address range to find its nearest key.':'This is the rule’s own position.';
 for(const [name,value] of [['key',state.selected],['x',p.x],['y',p.y],['r',p.r],['deg',p.deg]]){const el=$('particle-'+name);if(el&&document.activeElement!==el)el.value=editNumber(value);}
 $('parameter-note').textContent=(state.unsafeInput?'ABOVE 2^53: THE COMPUTER CANNOT COUNT EVERY KEY EXACTLY. Your typed value is preserved. ':'')+L.describe(params()).join(' ')+' Quiet time: '+number(params().skipPerSecond)+' keys per second, at most '+number(params().capSeconds)+' seconds. No per-particle coordinate table is saved.';
 const fm=$('mobile-formula');if(fm)fm.textContent=$('formula-radius').textContent;
}
function directionOf(deg){return ['right','up and right','up','up and left','left','down and left','down','down and right'][Math.round(deg/45)%8]||'at the centre';}
function findInterval(k){const a=DATA?.intervals||[];let lo=0,hi=a.length-1;while(lo<=hi){const m=(lo+hi)>>1,v=a[m];if(k<v.start)hi=m-1;else if(k>=v.end)lo=m+1;else return v;}return null;}
const fieldSpecs=[['first','First key'],['count','How many particles'],['turnNumber','Turn number'],['wrap','Wrap size'],['degreesPerKey','Degrees per key (blank uses turn / wrap)'],['power','How fast it spreads out (power)'],['offset','Start offset'],['skipPerSecond','Keys skipped per second'],['capSeconds','Longest quiet counted (seconds; 14 days = 1209600)'],['workLines','Lines per work burst'],['restSeconds','Seconds of rest between bursts'],['dotSize','Dot size in pixels'],['scale','Drawing scale']];
function fieldChange(name,text){stopWonder();state.unsafeInput=unsafeIntegerText(text);const value=name==='degreesPerKey'&&String(text).trim()===''?null:numeric(text);setParams({[name]:value},{smooth:false});params()._raw[name]=text;if(state.unsafeInput){status('ABOVE 2^53: THE COMPUTER CANNOT COUNT EVERY KEY EXACTLY.');log('Set '+name+' = '+text,'Value preserved. Whole-number precision is exhausted.');}sync();}
for(const [name,label] of fieldSpecs){const lab=document.createElement('label');lab.textContent=label;const input=document.createElement('input');input.type='text';input.inputMode='decimal';input.id='param-'+name;input.dataset.param=name;input.autocomplete='off';input.addEventListener('input',()=>fieldChange(name,input.value));lab.append(input);$('parameter-fields').append(lab);}
for(const [name,label] of [['key','Key'],['x','X: how far across'],['y','Y: how far up'],['r','Distance from centre'],['deg','Degrees from 3 o’clock, anticlockwise']]){const lab=document.createElement('label');lab.textContent=label;const input=document.createElement('input');input.id='particle-'+name;input.type='text';input.inputMode='decimal';input.addEventListener('input',()=>{const p=currentPoint(),v=numeric(input.value);if(name==='key'){if(unsafeIntegerText(input.value)){status('ABOVE 2^53: THE COMPUTER CANNOT COUNT EVERY KEY EXACTLY.');return;}selectKey(v);}else if(name==='x')moveSelected(v,p.y);else if(name==='y')moveSelected(p.x,v);else if(name==='r')movePolar(v,p.deg);else movePolar(p.r,v);});lab.append(input);$('particle-fields').append(lab);}
const sentences=["Place the first 100 lines of Kuiper's own code","Show every repeated line in the same colour","Take a night off","Go to key 12","Try turn 360","Show the circle with 1 trillion dots","Show me the wonder","Measure this against the real Kuiper code","Reset to the real Kuiper","Show a sunflower","Show 4 spokes","Show 3 spokes","Show 5 spokes","Show spiral arms","Show a crowded centre","Show dark rings","Show the 2^53 blob","Magnify this particle","Play","Pause","Step","Faster","Slower","Show the formulas","Help"];
for(const sentence of sentences){const b=document.createElement('button');b.textContent=sentence;b.addEventListener('click',()=>{$('commands-dialog').close();executeCommand(sentence);});$('sentences').append(b);}
function openDialog(id){stopWonder();const el=$(id);if(!el.open)el.showModal();sync();}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
function reset(){stopWonder();state.playing=false;state.code=false;state.colour='age';state.magnifier=false;state.realEstate=false;state.selected=0;state.revealed=1;state.lever=5;state.unsafeInput=false;setParams({...L.defaults(),first:0},{smooth:true});status('THE REAL KUIPER. Keys start at 0. The live radius includes 0.5.');log('Reset to the real Kuiper','Every field restored. Shared live placement law.');}
function nextLever(){stopWonder();state.lever=Math.min(5,state.lever+1);state.shadows=state.lever>=3;const messages=['Turn it. Full laps are thrown away.','Key 2: change its distance with the spread control.','Press Play. Keys 1 to 20 arrive one at a time.','X is across. Y is up. The shadows show both.','Take a rest. Skipped addresses become a dark ring.','Compare YOUR SPIRAL with THE REAL KUIPER.'];if(state.lever===1){setParams({first:2,count:1});state.selected=2;}if(state.lever===2){state.playing=false;state.revealed=1;setParams({first:1,count:1});}sync();status(messages[state.lever]);const target=document.querySelector('[data-level="'+state.lever+'"]');target?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'start'});invalidate();}
function grow(n){state.code=false;state.playing=false;state.magnifier=false;state.revealed=n;setParams({first:0,count:n,restSeconds:0});state.selected=n===1?0:Math.min(20,n-1);sync();}
function preset(kind){const shapes={sunflower:{...L.defaults(),first:0,count:1000},'4 spokes':{degreesPerKey:90},'3 spokes':{degreesPerKey:120},'5 spokes':{degreesPerKey:72},'spiral arms':{degreesPerKey:91},'crowded centre':{power:1},'dark rings':{workLines:100,restSeconds:4,skipPerSecond:600,capSeconds:1209600}};state.playing=false;state.code=false;setParams({...L.defaults(),first:0,count:1000,...shapes[kind]});hint(kind);}
async function measure(){if(state.proving)return;state.proving=true;status('Measuring the shared live law across 1,000,000 keys.');let photons=0,max=0;const started=performance.now(),p=L.defaults();for(let base=0;base<1000000;base+=20000){for(let k=base;k<base+20000;k++){const a=KuiperLaw.keyPlace(k),b=L.place(k,p);const d=Math.max(Math.abs(a[0]-b.x),Math.abs(a[1]-b.y));max=Math.max(max,d);if(d!==0)photons++;}await new Promise(resolve=>setTimeout(resolve,0));}state.proof={cases:1000000,photons,max_abs_diff:max,witness:'KuiperLaw.keyPlace vs logic.place with real parameters',seeds:'0..999999',timing:performance.now()-started};state.proving=false;const line='CHECKED 1,000,000 KEYS: '+number(photons)+' DIFFERENCES';status(line);log('Measure this against the real Kuiper code',line+' · Real settings.');return state.proof;}
function executeCommand(text){stopWonder();const original=String(text).trim(),s=original.toLowerCase().replaceAll('’',"'").replace(/[,.](?=\d{3}(\D|$))/g,'');let result='';
 if(/measure.*real kuiper|^prove$/.test(s)){measure();return 'Measuring';}
 if(/reset|^real kuiper$/.test(s)){reset();return 'Reset';}
 if(/wonder/.test(s)){startWonder();return 'Wonder';}
 if(/first\s+\d+\s+lines|own code|^code$/.test(s)){const n=Number(s.match(/first\s+(\d+)/)?.[1]||100);state.code=true;state.colour='duplicate';state.playing=false;state.revealed=n;setParams({first:0,count:n,restSeconds:0});state.selected=Math.min(1,n-1);result='Real source lines in order. These are example addresses, not historical estate keys.';}
 else if(/repeated|duplicate/.test(s)){state.code=true;state.colour='duplicate';state.revealed=Math.max(100,Math.min(DATA.lines.length,params().count));setParams({first:0,count:state.revealed,restSeconds:0});result='Identical source text has the same colour. Every copy keeps its own address.';}
 else if(/night off/.test(s)){setParams({restSeconds:8*3600,workLines:Math.max(1,Math.min(20,params().count)),count:Math.max(60,params().count)});result='Eight hours of quiet: '+number(8*3600*params().skipPerSecond)+' addresses skipped between bursts.';hint('quiet');}
 else if(/go to key|^key /.test(s)){const k=numeric(s.match(/(?:go to key|key)\s+(.+)/)?.[1]||'');selectKey(k);const b=L.bounds(params());if(b.valid&&(k<b.first||k>b.last))setParams({first:k,count:1});state.magnifier=true;result='Key '+number(k)+'. Its true place is computed directly.';}
 else if(/turn\s+[-+\d.]/.test(s)){const n=numeric(s.match(/turn\s+([^\s]+)/)?.[1]);setParams({degreesPerKey:n,count:params().count===1?100:params().count});result=n%360===0?'Every dot lands on one line. Full laps change no direction.':'Each successive key turns '+number(n)+' degrees.';hint('turn');}
 else if(/2\^53|2\*\*53/.test(s)){setParams({...L.defaults()},{smooth:false,quiet:true});grow(2**53);state.lever=5;result='2^53 ADDRESSED. Zoom in for detail; whole-number precision ends here.';}
 else if(/circle with|^count /.test(s)){const m=s.match(/(?:with|count)\s+([\d.e+\-]+)\s*(quadrillion|trillion|billion|million|thousand)?/);if(m){let n=Number(m[1])*({quadrillion:1e15,trillion:1e12,billion:1e9,million:1e6,thousand:1e3}[m[2]]||1);grow(n);result=L.describe(params()).join(' ');if(n>=1e12)milestone(n);}else result='Say: Show the circle with 1 trillion dots.';}
 else if(/sunflower/.test(s)){preset('sunflower');result='The real Kuiper placement law.';}
 else if(/(4|3|5) spokes/.test(s)){const k=s.match(/(4|3|5) spokes/)[0];preset(k);result=k.toUpperCase()+': THE TURN DIVIDES A FULL CIRCLE.';}
 else if(/spiral arms|crowded centre|dark rings/.test(s)){const k=s.match(/spiral arms|crowded centre|dark rings/)[0];preset(k);result=k==='crowded centre'?'Linear radius: the centre is denser; the outer region is sparser.':k==='dark rings'?'Quiet addresses stay empty. The next work starts further out.':'91 degrees twists four spokes into arms.';}
 else if(/magnif/.test(s)){state.magnifier=!state.magnifier;result=state.magnifier?'A local window: true neighbours are calculated, not sampled.':'Back to the whole address range.';}
 else if(s==='play'){playToggle(true);result='New real source lines land one by one.';}
 else if(s==='pause'){playToggle(false);result='Paused.';}
 else if(s==='step'){step();result='One more line.';}
 else if(s==='faster'||s==='slower'){state.speed=s==='faster'?Math.min(100,state.speed*2):Math.max(.25,state.speed/2);result=number(state.speed)+' lines per second.';}
 else if(/formulas|numbers/.test(s)){openDialog('numbers-dialog');result='Every field is editable. Changes act live.';}
 else if(s==='help'||s==='/'){openDialog('commands-dialog');result='Pick one plain sentence.';}
 else result='Try a sentence from Commands, such as “Try turn 360”.';
 log(original,result);status(result);sync();invalidate();return result;
}
function playToggle(force){state.playing=force===undefined?!state.playing:force;if(state.playing&&!state.code)state.playLimit=params().count<20?20:params().count+20;if(state.playing&&state.code&&state.revealed>=params().count)state.revealed=1;lastPlay=performance.now();sync();invalidate();}
function step(){if(!state.code){setParams({count:params().count+1},{smooth:false,quiet:true});state.revealed=params().count;selectKey(L.addressForIndex(params().count-1,params()));}else{state.revealed=Math.min(params().count,state.revealed+1);selectKey(L.addressForIndex(state.revealed-1,params()));}SOUND.tone(state.selected,truePoint().r);invalidate();}
const wonderCounts=[1,10,100,1000000,43486619138,1e12];
function startWonder(){setParams({...L.defaults(),first:1},{smooth:false,quiet:true});state.playing=false;state.code=false;state.magnifier=false;state.shadows=false;state.lever=5;state.wonder=true;state.wonderStart=performance.now();state.wonderIndex=-1;$('wonder').hidden=false;sync();invalidate();}
function endWonder(){state.wonder=false;$('wonder').hidden=true;setParams({...L.defaults()},{smooth:false,quiet:true});grow(1e12);status('ALL OF THIS FROM ONE NUMBER AND ONE RULE. NO COORDINATES STORED.');log('Show me the wonder','1 trillion addressed. No per-particle coordinate table.');try{localStorage.setItem('kuiper-codex-wonder','seen');}catch(e){}}
function milestone(n){status(compact(n).toUpperCase()+' ADDRESSED. NO COORDINATE TABLE.');SOUND.tone(n,Math.sqrt(n));}
const hints=['Drag the dot. Its true place stays marked.','Distance means how far from the centre.','Angles start at 3 o’clock and increase anticlockwise.','One full turn is 360 degrees.','90 degrees makes four spokes.','120 degrees makes three spokes.','72 degrees makes five spokes.','91 degrees bends four spokes into arms.','A square root lets area grow with the address count.','Linear radius crowds the centre, not the rim.','Quiet addresses stay empty.','A night off becomes a dark ring.','The same quiet gap makes a thinner band further out.','The live radius includes a half-key offset.','The integer turn repeats after 2³² keys.','Repeated code stays repeated. Each copy has its own key.','Large views use a fair sample, never trillions of stored dots.','The magnifier computes local neighbours.','The real rule returns the same position for the same key.','Real Kuiper brings every number back to the original rule.'];
function hint(action){const now=Date.now();let index=0;try{lastHint=Math.max(lastHint,Number(localStorage.getItem('kuiper-codex-hint-time')||0));index=Number(localStorage.getItem('kuiper-codex-hint')||0)%hints.length;}catch(e){}if(now-lastHint<20000)return;lastHint=now;try{localStorage.setItem('kuiper-codex-hint',String(index+1));localStorage.setItem('kuiper-codex-hint-time',String(now));}catch(e){}const context={'4 spokes':4,'3 spokes':5,'5 spokes':6,'spiral arms':7,'crowded centre':9,'dark rings':10,quiet:11,turn:3};$('hint').textContent=hints[context[action]??index];$('hint').hidden=false;clearTimeout(hintTimer);hintTimer=setTimeout(()=>$('hint').hidden=true,6000);}
function pointColour(pt,i,n){const pal=palettes[state.palette];if(state.colour==='duplicate'&&state.code){const line=DATA.lines[Math.max(0,Math.min(DATA.lines.length-1,pt.index??Math.round(pt.key-params().first)))];const group=line?.duplicateGroup;let h=0;for(const c of String(group??line?.text??''))h=(Math.imul(h,31)+c.charCodeAt(0))>>>0;return pal[h%pal.length];}if(state.colour==='turn')return pal[Math.min(4,Math.floor(pt.deg/72))];return pal[Math.min(4,Math.floor(i/Math.max(1,n)*5))];}
function project(p){return {x:cam.cx+(p.x-cam.x)*cam.s,y:cam.cy-(p.y-cam.y)*cam.s};}
function world(x,y){return {x:(x-cam.cx)/cam.s+cam.x,y:(cam.cy-y)/cam.s+cam.y};}
function resize(){const r=$('drawing').getBoundingClientRect();width=r.width;height=r.height;const dpr=Math.min(devicePixelRatio||1,2.5);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);g.setTransform(dpr,0,0,dpr,0,0);invalidate();}
function draw(t){g.clearRect(0,0,width,height);g.fillStyle='#000';g.fillRect(0,0,width,height);const phone=width<700,p=params(),b=L.bounds(p),pal=palettes[state.palette];const viewW=phone?width:width-350;const top=phone?122:60,bottom=phone?174:94;const usable=Math.max(80,height-top-bottom);cam.cx=viewW/2;cam.cy=top+usable/2;const R=Math.max(24,Math.min(viewW*.37,usable*.42));const bound=Math.max(2,b.radius||2),scale=Number.isFinite(p.scale)?p.scale:1;cam.s=R/bound*scale;cam.x=0;cam.y=0;
 const selected=currentPoint();let neighbourInfo=null;if(state.magnifier&&selected.valid){cam.x=selected.x;cam.y=selected.y;cam.s=R/3*Math.abs(scale||1);try{neighbourInfo=L.neighbours(selected.x,selected.y,3,p,350);sample=neighbourInfo;}catch(e){sample=[];} }else{const cp=state.playing||state.code?L.normalize({...p,count:Math.min(p.count,state.revealed)}):p;sample=L.sample(cp,phone?1200:2400);}
 g.strokeStyle='#12414a';g.lineWidth=1;g.setLineDash([]);g.beginPath();g.moveTo(cam.cx-R-16,cam.cy);g.lineTo(cam.cx+R+16,cam.cy);g.moveTo(cam.cx,cam.cy-R-16);g.lineTo(cam.cx,cam.cy+R+16);g.stroke();for(const fraction of [.5,1]){g.beginPath();g.arc(cam.cx,cam.cy,R*fraction,0,TAU);g.stroke();}g.fillStyle='#66ccff';g.font='700 '+(phone?24:24)+'px monospace';g.textAlign='center';g.fillText('0°',Math.min(viewW-30,cam.cx+R+32),cam.cy+8);g.fillText('90°',cam.cx,phone?cam.cy-R+26:cam.cy-R-20);
 hit=[];let drawn=0;const morph=state.morph?Math.min(1,(t-state.morph.t)/700):1;const size=Number.isFinite(p.dotSize)&&p.dotSize>0?Math.min(p.dotSize,Math.max(width,height)*2):0;
 for(let i=0;i<sample.length;i++){let pt=sample[i];if(!pt.valid)continue;let displayed=pt;if(morph<1&&!state.magnifier){const old=L.place(pt.key,state.morph.from);if(old.valid){const u=morph*morph*(3-2*morph);displayed={x:old.x+(pt.x-old.x)*u,y:old.y+(pt.y-old.y)*u};}}const pos=project(displayed);if(!Number.isFinite(pos.x)||!Number.isFinite(pos.y)||pos.x<-size||pos.y<-size||pos.x>viewW+size||pos.y>height+size)continue;g.fillStyle=pointColour(pt,i,sample.length);g.beginPath();g.arc(pos.x,pos.y,size/2,0,TAU);g.fill();hit.push({key:pt.key,x:pos.x,y:pos.y});drawn++;}
 if(morph>=1)state.morph=null;
 const truth=truePoint();if(truth.valid){const q=project(truth);if(state.practice){g.strokeStyle=pal[1];g.beginPath();g.moveTo(q.x-7,q.y);g.lineTo(q.x+7,q.y);g.moveTo(q.x,q.y-7);g.lineTo(q.x,q.y+7);g.stroke();const moved=project(selected);g.setLineDash([6,6]);g.beginPath();g.moveTo(q.x,q.y);g.lineTo(moved.x,moved.y);g.stroke();g.setLineDash([]);}}
 if(selected.valid){const q=project(selected);if(q.x>-100&&q.x<viewW+100&&q.y>-100&&q.y<height+100){g.strokeStyle=pal[2];g.lineWidth=2;g.beginPath();g.moveTo(cam.cx,cam.cy);g.lineTo(q.x,q.y);g.stroke();if(state.shadows){g.setLineDash([5,5]);g.strokeStyle=pal[1];g.beginPath();g.moveTo(q.x,cam.cy);g.lineTo(q.x,q.y);g.lineTo(cam.cx,q.y);g.stroke();g.setLineDash([]);g.fillStyle='#fff';g.font='700 24px monospace';g.textAlign='left';g.fillText('X '+number(selected.x),Math.max(8,cam.cx-70),cam.cy+32);g.fillText('Y '+number(selected.y),8,Math.max(120,q.y));}g.fillStyle=pal[2];g.beginPath();g.arc(q.x,q.y,Math.max(7,size/2+2),0,TAU);g.fill();g.strokeStyle=pal[0];g.beginPath();g.arc(q.x,q.y,15+(t<3500?3*Math.sin(t/170):0),0,TAU);g.stroke();const lx=phone?12:24,ly=phone?162:112;g.beginPath();g.moveTo(q.x,q.y);g.lineTo(lx+20,ly+12);g.lineTo(lx,ly+12);g.stroke();g.fillStyle='#fff';g.textAlign='left';g.font='700 '+(phone?28:40)+'px monospace';g.fillText('KEY '+compact(state.selected),lx,ly);}}
 if(!b.valid){g.fillStyle=pal[2];g.textAlign='center';g.font='700 24px monospace';wrapCanvas(b.reason||'No finite drawing for these numbers.',cam.cx,cam.cy,Math.max(120,viewW-30),30);}
 if(state.magnifier){$('sample-label').textContent=sample.certified&&!sample.truncated?'ALL '+sample.length+' TRUE NEIGHBOURS IN THIS WINDOW.':(sample.reason||'Local search is incomplete for these settings.');status(sample.certified&&!sample.truncated?'The circle grows. This local window is calculated at full detail.':'Local search: '+(sample.reason||'uncertified'));}
 if(!state.magnifier&&p.count>sample.length&&b.valid&&!state.wonder)$('sample-label').textContent=phone?number(drawn)+' DOTS / SAMPLED':number(drawn)+' SCREEN DOTS / '+compact(p.count)+' ADDRESSED.';
}
function wrapCanvas(text,x,y,w,lineHeight){const words=text.split(' ');let line='',row=0;for(const word of words){const test=line+word+' ';if(g.measureText(test).width>w&&line){g.fillText(line,x,y+row++*lineHeight);line=word+' ';}else line=test;}g.fillText(line,x,y+row*lineHeight);}
function tick(t){if(state.wonder){const elapsed=t-state.wonderStart,index=Math.min(wonderCounts.length-1,Math.floor(elapsed/3300));if(index!==state.wonderIndex){state.wonderIndex=index;const n=wonderCounts[index];state.revealed=n;setParams({first:index===0?1:0,count:n,restSeconds:0},{quiet:true});state.selected=index===0?1:Math.min(20,n-1);$('wonder-label').textContent=compact(n).toUpperCase()+' PARTICLES';}if(Math.floor(elapsed/650)!==state.musicBeat){state.musicBeat=Math.floor(elapsed/650);SOUND.tone(state.musicBeat,Math.sqrt(params().count));}if(elapsed>=20000)endWonder();}if(state.playing&&t-lastPlay>=1000/state.speed){lastPlay=t;step();if(state.code?state.revealed>=params().count:params().count>=state.playLimit){state.playing=false;sync();}}if(dirty||state.morph||state.wonder||state.playing||t<3500){draw(t);dirty=false;}frame=requestAnimationFrame(tick);}
function canvasPosition(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.addEventListener('pointerdown',e=>{const p=canvasPosition(e);let nearest=null,d=28;for(const h of hit){const n=Math.hypot(h.x-p.x,h.y-p.y);if(n<d){d=n;nearest=h;}}const active=project(currentPoint());if(Math.hypot(active.x-p.x,active.y-p.y)<30)nearest={key:state.selected};if(nearest)selectKey(nearest.key);else{const w=world(p.x,p.y);moveSelected(w.x,w.y);}drag={x:p.x,y:p.y,moved:false,selected:!!nearest};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=canvasPosition(e);if(Math.hypot(p.x-drag.x,p.y-drag.y)>3)drag.moved=true;if(drag.moved){const w=world(p.x,p.y);moveSelected(w.x,w.y);}});
canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved&&drag.selected)openDialog('particle-dialog');drag=null;});canvas.addEventListener('pointercancel',()=>drag=null);
canvas.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const p=currentPoint(),v=10/Math.max(Math.abs(cam.s),1e-20);moveSelected(p.x+(e.key==='ArrowRight'?v:e.key==='ArrowLeft'?-v:0),p.y+(e.key==='ArrowUp'?v:e.key==='ArrowDown'?-v:0));}if(e.key==='Enter')openDialog('particle-dialog');});
document.addEventListener('keydown',e=>{const editing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName);if(e.key==='/'&&!editing){e.preventDefault();openDialog('commands-dialog');}if(e.key==='Escape')stopWonder();});
$('angle').addEventListener('input',()=>fieldChange('degreesPerKey',$('angle').value));$('lever-power').addEventListener('input',()=>fieldChange('power',$('lever-power').value));$('lever-count').addEventListener('input',()=>{fieldChange('count',$('lever-count').value);state.revealed=params().count;invalidate();});$('lever-quiet').addEventListener('input',()=>{state.revealed=Math.max(100,params().count);setParams({count:Math.max(100,params().count),workLines:20});fieldChange('restSeconds',$('lever-quiet').value);});$('next-lever').onclick=nextLever;$('switch-real').onclick=()=>{const count=params().count;reset();setParams({count,first:0});};$('shadows').onclick=()=>{state.shadows=!state.shadows;invalidate();};
$('reset').onclick=reset;$('reset-numbers').onclick=reset;$('commands').onclick=()=>openDialog('commands-dialog');$('numbers').onclick=()=>openDialog('numbers-dialog');$('inspect').onclick=()=>openDialog('particle-dialog');$('restore-dot').onclick=()=>{state.practice=null;state.nearest=null;sync();invalidate();};$('magnify').onclick=()=>executeCommand('Magnify this particle');$('play').onclick=()=>playToggle();$('step').onclick=step;$('faster').onclick=()=>executeCommand('Faster');$('slower').onclick=()=>executeCommand('Slower');$('skip').onclick=()=>{stopWonder();status('Your drawing. Every number is yours.');};$('command-form').addEventListener('submit',e=>{e.preventDefault();executeCommand($('command').value);$('command').value='';});
$('palette').onchange=e=>{state.palette=e.target.value;invalidate();};$('colour').onchange=e=>{state.colour=e.target.value;invalidate();};$('mood').onchange=e=>SOUND.setMood(e.target.value);$('mute').onclick=()=>{$('mute').textContent=SOUND.setMuted(!SOUND.muted)?'Sound off':'Sound on';};function textSize(v){state.text=Math.max(24,Math.min(40,v));document.documentElement.style.setProperty('--text',state.text+'px');document.documentElement.style.setProperty('--caption',Math.max(width<700?28:40,state.text+4)+'px');invalidate();}$('text-up').onclick=()=>textSize(state.text+4);$('text-down').onclick=()=>textSize(state.text-4);
function setScene(name){document.querySelectorAll('dialog[open]').forEach(d=>d.close());stopWonder();reset();state.lever=0;setParams({...L.defaults(),first:1,offset:0,degreesPerKey:137.5},{smooth:false});state.selected=1;state.morph=null;log('Move the dot.','1,100,009 KEYS: 0 DIFFS');$('hint').hidden=true;switch(name){case'moved-particle':moveSelected(.8,1.1);break;case'one-trillion':state.lever=5;setParams({...L.defaults()},{smooth:false,quiet:true});grow(1e12);break;case'turn-360':state.lever=2;setParams({first:0,count:100,degreesPerKey:360},{smooth:false});break;case'code-duplicates':state.lever=2;executeCommand("Place the first 100 lines of Kuiper's own code");break;case'commands':openDialog('commands-dialog');break;case'wonder-end':state.lever=5;endWonder();break;}if(/^lever-[0-5]$/.test(name)){state.lever=Number(name.at(-1));state.shadows=state.lever>=3;if(state.lever===1){setParams({first:2,count:1},{smooth:false});state.selected=2;}if(state.lever>=2)setParams({count:20},{smooth:false});if(state.lever===4)setParams({count:100,workLines:20,restSeconds:4},{smooth:false});if(state.lever===5){setParams({...L.defaults(),count:100},{smooth:false});state.selected=7;}}state.morph=null;sync();status(state.lever===0?"0 IS AT 3 O'CLOCK. ANGLES TURN ANTICLOCKWISE.":L.isReal(params())?'THE REAL KUIPER. Shared live placement law.':'YOUR SPIRAL. Change a number and watch.');if(name==='wonder-end')status('ALL OF THIS FROM ONE NUMBER AND ONE RULE. NO COORDINATES STORED.');invalidate();return state;}
window.KuiperApp={state,getState:()=>state,setParams,selectKey,moveSelected,executeCommand,startWonder,endWonder,setScene,nextLever,measure,draw:()=>{draw(performance.now());return hit;},screenPoint:()=>project(currentPoint())};
new ResizeObserver(resize).observe($('drawing'));sync();resize();status("0 IS AT 3 O'CLOCK. ANGLES TURN ANTICLOCKWISE.");$('proof-line').textContent=innerWidth<700?'1,100,009 KEYS: 0 DIFFS':'REAL LAW: 1,100,009 keys checked. 0 differences.';frame=requestAnimationFrame(tick);
})();
